name: Publish

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-n-publish:
    name: Build and publish plugin to JetBrains Marketplace
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17
      - name: Test
        run: xvfb-run -a ./gradlew test jacocoTestReport
      - name: Build plugin
        run: xvfb-run -a ./gradlew buildPlugin
      - name: Create GitHub release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh release create "$GITHUB_REF_NAME" ./build/distributions/strawberry-pycharm-plugin.zip --title "Release $GITHUB_REF_NAME" --notes "Release $GITHUB_REF_NAME"
      - name: Publish plugin
        run: xvfb-run -a ./gradlew publishPlugin
        env:
          ORG_GRADLE_PROJECT_intellijPublishToken: ${{ secrets.ORG_GRADLE_PROJECT_INTELLIJPUBLISHTOKEN }}
