name: Test

on:
  pull_request: {}
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache
      uses: actions/cache@v1.1.2
      with:
        path: ~/.gradle
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/build.gradle') }}
        restore-keys: |
          ${{ runner.os }}-gradle-
    - name: Setup Java
      uses: actions/setup-java@v3.9.0
      with:
        distribution: zulu
        java-version: 17
    - name: test 
      run: ./gradlew buildPlugin test jacocoTestReport
    - name: Verify Plugin on IntelliJ Platforms
      id: verify
      uses: ChrisCarini/intellij-platform-plugin-verifier-action@latest
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        ide-versions: |
          pycharmPC:2022.2
          pycharmPC:LATEST-EAP-SNAPSHOT

    - name: Get log file path and print contents
      run: |
        echo "The verifier log file [${{steps.verify.outputs.verification-output-log-filename}}] contents : " ;
        cat ${{steps.verify.outputs.verification-output-log-filename}}
